name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test VCPKG Auto Build Scripts
        shell: bash
        run: |
          REPO_ROOT="$GITHUB_WORKSPACE"
          (cd $REPO_ROOT | ./autobuild.sh)

      - name: Collect artifacts with directory structure
        run: |
          REPO_ROOT="$GITHUB_WORKSPACE"
          mkdir -p artifacts
          find "$REPO_ROOT" -type f -path "*/SampleCode/*.bin" -exec cp --parents {} artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: samplecode-artifacts
          path: artifacts/
