name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python-is-python3

      - name: Activate & Build each csolution
        shell: bash
        run: |
          REPO_ROOT="$GITHUB_WORKSPACE"

      - name: Collect artifacts with directory structure
        run: |
          mkdir -p artifacts
          find SampleCode -type f -name "*.bin" -exec cp --parents {} artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: samplecode-artifacts
          path: artifacts/
